// <auto-generated />
using System;
using ManningApi.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ManningApi.Migrations
{
    [DbContext(typeof(ManningDbContext))]
    [Migration("20230611191039_PostgresSetup")]
    partial class PostgresSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ManningApi.Models.ClockModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("ClockCardNumber")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ClockInTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ClockOutTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID");

                    b.ToTable("ClockModel");
                });

            modelBuilder.Entity("ManningApi.Models.OpStation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("ZoneID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("ZoneID");

                    b.ToTable("OpStation");
                });

            modelBuilder.Entity("ManningApi.Models.Operator", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ClockCardNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAdministrator")
                        .HasColumnType("boolean");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID");

                    b.ToTable("Operator");
                });

            modelBuilder.Entity("ManningApi.Models.OperatorCompletedTraining", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("OperatorID")
                        .HasColumnType("integer");

                    b.Property<int>("TrainerClockCardNumber")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingRequirementID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("OperatorCompletedTraining");
                });

            modelBuilder.Entity("ManningApi.Models.ShiftType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID");

                    b.ToTable("ShiftType");
                });

            modelBuilder.Entity("ManningApi.Models.TrainingRequirement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("OpStationID")
                        .HasColumnType("integer");

                    b.Property<string>("RequirementDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TrainingRequirementTypeId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("OpStationID");

                    b.HasIndex("TrainingRequirementTypeId");

                    b.ToTable("TrainingRequirement");
                });

            modelBuilder.Entity("ManningApi.Models.TrainingRequirementType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("TrainingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID");

                    b.ToTable("TrainingRequirementsType");
                });

            modelBuilder.Entity("ManningApi.Models.WorkingDayHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("OpStationID")
                        .HasColumnType("integer");

                    b.Property<int>("OperatorID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ShiftID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("OpStationID");

                    b.HasIndex("OperatorID");

                    b.HasIndex("ShiftID");

                    b.ToTable("WorkdayHistory");
                });

            modelBuilder.Entity("ManningApi.Models.Zone", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID");

                    b.ToTable("Zone");
                });

            modelBuilder.Entity("ManningApi.Models.OpStation", b =>
                {
                    b.HasOne("ManningApi.Models.Zone", null)
                        .WithMany("OpStations")
                        .HasForeignKey("ZoneID");
                });

            modelBuilder.Entity("ManningApi.Models.TrainingRequirement", b =>
                {
                    b.HasOne("ManningApi.Models.OpStation", null)
                        .WithMany("TrainingRequirements")
                        .HasForeignKey("OpStationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManningApi.Models.TrainingRequirementType", "TrainingRequirementType")
                        .WithMany()
                        .HasForeignKey("TrainingRequirementTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingRequirementType");
                });

            modelBuilder.Entity("ManningApi.Models.WorkingDayHistory", b =>
                {
                    b.HasOne("ManningApi.Models.OpStation", "OpStation")
                        .WithMany()
                        .HasForeignKey("OpStationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManningApi.Models.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManningApi.Models.ShiftType", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpStation");

                    b.Navigation("Operator");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ManningApi.Models.OpStation", b =>
                {
                    b.Navigation("TrainingRequirements");
                });

            modelBuilder.Entity("ManningApi.Models.Zone", b =>
                {
                    b.Navigation("OpStations");
                });
#pragma warning restore 612, 618
        }
    }
}
