import Header from '@/src/components/Header';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="en">
      <Header />
      <body>{children}</body>
    </html>
  );
}

//type NavBarWrapperProps = { children: ReactNode }

//const NavBarWrapper: NavBarWrapperProps = ({ children }): ReactNode => {
//return (
//<div>
//{children}
//</div>
//);
//};
