import "@/src/styles/globals.css";
import Header from "@/src/components/Header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="">{children}</main>
      </body>
    </html>
  );
}
