// // <auto-generated />
// using System;
// using ManningApi.Repositories;
// using Microsoft.EntityFrameworkCore;
// using Microsoft.EntityFrameworkCore.Infrastructure;
// using Microsoft.EntityFrameworkCore.Metadata;
// using Microsoft.EntityFrameworkCore.Migrations;
// using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

// #nullable disable

// namespace ManningApi.Migrations
// {
//     [DbContext(typeof(ManningDbContext))]
//     [Migration("20230604231618_ClockInSupport")]
//     partial class ClockInSupport
//     {
//         protected override void BuildTargetModel(ModelBuilder modelBuilder)
//         {
// #pragma warning disable 612, 618
//             modelBuilder
//                 .HasAnnotation("ProductVersion", "6.0.13")
//                 .HasAnnotation("Relational:MaxIdentifierLength", 128);

//             SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

//             modelBuilder.Entity("ManningApi.Models.ClockModel", b =>
//                 {
//                     b.Property<int>("ID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

//                     b.Property<int?>("ClockCardNumber")
//                         .IsRequired()
//                         .HasColumnType("int");

//                     b.Property<DateTime?>("ClockInTime")
//                         .HasColumnType("datetime2");

//                     b.Property<DateTime?>("ClockOutTime")
//                         .HasColumnType("datetime2");

//                     b.Property<string>("OperatorName")
//                         .IsRequired()
//                         .HasMaxLength(50)
//                         .HasColumnType("nvarchar(50)");

//                     b.HasKey("ID");

//                     b.ToTable("ClockModel");
//                 });

//             modelBuilder.Entity("ManningApi.Models.Operator", b =>
//                 {
//                     b.Property<int>("ID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

//                     b.Property<int>("ClockCardNumber")
//                         .HasColumnType("int");

//                     b.Property<bool>("IsAdministrator")
//                         .HasColumnType("bit");

//                     b.Property<string>("OperatorName")
//                         .IsRequired()
//                         .HasMaxLength(50)
//                         .HasColumnType("nvarchar(50)");

//                     b.HasKey("ID");

//                     b.ToTable("Operator");
//                 });

//             modelBuilder.Entity("ManningApi.Models.OperatorCompletedTraining", b =>
//                 {
//                     b.Property<int>("ID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

//                     b.Property<int>("OperatorID")
//                         .HasColumnType("int");

//                     b.Property<int>("TrainerClockCardNumber")
//                         .HasColumnType("int");

//                     b.Property<int>("TrainingRequirementID")
//                         .HasColumnType("int");

//                     b.HasKey("ID");

//                     b.ToTable("OperatorCompletedTraining");
//                 });

//             modelBuilder.Entity("ManningApi.Models.Station", b =>
//                 {
//                     b.Property<int>("ID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

//                     b.Property<string>("StationName")
//                         .IsRequired()
//                         .HasMaxLength(20)
//                         .HasColumnType("nvarchar(20)");

//                     b.Property<int?>("ZoneID")
//                         .HasColumnType("int");

//                     b.HasKey("ID");

//                     b.HasIndex("ZoneID");

//                     b.ToTable("Station");
//                 });

//             modelBuilder.Entity("ManningApi.Models.ShiftType", b =>
//                 {
//                     b.Property<int>("ID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

//                     b.Property<string>("ShiftName")
//                         .IsRequired()
//                         .HasMaxLength(50)
//                         .HasColumnType("nvarchar(50)");

//                     b.HasKey("ID");

//                     b.ToTable("ShiftType");
//                 });

//             modelBuilder.Entity("ManningApi.Models.TrainingRequirement", b =>
//                 {
//                     b.Property<int>("ID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

//                     b.Property<int>("OpStationID")
//                         .HasColumnType("int");

//                     b.Property<string>("RequirementDescription")
//                         .IsRequired()
//                         .HasMaxLength(255)
//                         .HasColumnType("nvarchar(255)");

//                     b.Property<int>("TrainingRequirementTypeId")
//                         .HasColumnType("int");

//                     b.HasKey("ID");

//                     b.HasIndex("OpStationID");

//                     b.HasIndex("TrainingRequirementTypeId");

//                     b.ToTable("TrainingRequirement");
//                 });

//             modelBuilder.Entity("ManningApi.Models.TrainingRequirementType", b =>
//                 {
//                     b.Property<int>("ID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

//                     b.Property<string>("TrainingType")
//                         .IsRequired()
//                         .HasMaxLength(50)
//                         .HasColumnType("nvarchar(50)");

//                     b.HasKey("ID");

//                     b.ToTable("TrainingRequirementsType");
//                 });

//             modelBuilder.Entity("ManningApi.Models.WorkingDayHistory", b =>
//                 {
//                     b.Property<int>("ID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

//                     b.Property<int>("OpStationID")
//                         .HasColumnType("int");

//                     b.Property<int>("OperatorID")
//                         .HasColumnType("int");

//                     b.Property<DateTime>("ShiftDate")
//                         .HasColumnType("DateTime2");

//                     b.Property<int>("ShiftID")
//                         .HasColumnType("int");

//                     b.HasKey("ID");

//                     b.HasIndex("OpStationID");

//                     b.HasIndex("OperatorID");

//                     b.HasIndex("ShiftID");

//                     b.ToTable("WorkdayHistory");
//                 });

//             modelBuilder.Entity("ManningApi.Models.Zone", b =>
//                 {
//                     b.Property<int>("ID")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

//                     b.Property<string>("ZoneName")
//                         .IsRequired()
//                         .HasMaxLength(50)
//                         .HasColumnType("nvarchar(50)");

//                     b.HasKey("ID");

//                     b.ToTable("Zone");
//                 });

//             modelBuilder.Entity("ManningApi.Models.Station", b =>
//                 {
//                     b.HasOne("ManningApi.Models.Zone", null)
//                         .WithMany("OpStations")
//                         .HasForeignKey("ZoneID");
//                 });

//             modelBuilder.Entity("ManningApi.Models.TrainingRequirement", b =>
//                 {
//                     b.HasOne("ManningApi.Models.Station", null)
//                         .WithMany("TrainingRequirements")
//                         .HasForeignKey("OpStationID")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.HasOne("ManningApi.Models.TrainingRequirementType", "TrainingRequirementType")
//                         .WithMany()
//                         .HasForeignKey("TrainingRequirementTypeId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.Navigation("TrainingRequirementType");
//                 });

//             modelBuilder.Entity("ManningApi.Models.WorkingDayHistory", b =>
//                 {
//                     b.HasOne("ManningApi.Models.Station", "Station")
//                         .WithMany()
//                         .HasForeignKey("OpStationID")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.HasOne("ManningApi.Models.Operator", "Operator")
//                         .WithMany()
//                         .HasForeignKey("OperatorID")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.HasOne("ManningApi.Models.ShiftType", "Shift")
//                         .WithMany()
//                         .HasForeignKey("ShiftID")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.Navigation("Station");

//                     b.Navigation("Operator");

//                     b.Navigation("Shift");
//                 });

//             modelBuilder.Entity("ManningApi.Models.Station", b =>
//                 {
//                     b.Navigation("TrainingRequirements");
//                 });

//             modelBuilder.Entity("ManningApi.Models.Zone", b =>
//                 {
//                     b.Navigation("OpStations");
//                 });
// #pragma warning restore 612, 618
//         }
//     }
// }
