version: '3.1'

services:
  manningdb:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - '7003:5432'
    volumes:
      - manning-db:/var/lib/postgresql/data

volumes:
  manning-db:
